# Generated by Django 2.1 on 2018-08-22 07:03

from django.db import migrations
from mainapp.models import Person

def generate_unique_identifier(apps, schema_editor):
    for row in Person.objects.all():
        row.unique_identifier = row.generate_unique_identifier()
        row.save(update_fields=['unique_identifier'])


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0076_auto_20180822_1220'),
    ]

    operations = [
        migrations.RunPython(generate_unique_identifier, reverse_code=migrations.RunPython.noop),
    ]
