# Generated by Django 2.1 on 2018-08-22 07:03

from django.db import migrations
from mainapp.models import Person

class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0076_auto_20180822_1220'),
    ]

    operations = [
        migrations.RunSQL("CREATE UNIQUE INDEX unique_identifier_idx ON mainapp_person (unique_identifier) WHERE (unique_identifier is not null);")
    ]
